-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jan 17, 2025 at 09:51 AM
-- Server version: 8.2.0
-- PHP Version: 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `blog_emusic`
--

-- --------------------------------------------------------

--
-- Table structure for table `autor`
--

DROP TABLE IF EXISTS `autor`;
CREATE TABLE IF NOT EXISTS `autor` (
  `id_autor` int NOT NULL AUTO_INCREMENT,
  `nombre_autor` varchar(5) NOT NULL,
  `apellido_autor` varchar(6) NOT NULL,
  `email_autor` varchar(22) NOT NULL,
  `nombre_usuario_autor` varchar(8) NOT NULL,
  `contrasenha_autor` varchar(8) NOT NULL,
  PRIMARY KEY (`id_autor`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `autor`
--

INSERT INTO `autor` (`id_autor`, `nombre_autor`, `apellido_autor`, `email_autor`, `nombre_usuario_autor`, `contrasenha_autor`) VALUES
(1, 'Quino', 'Moreno', 'quinoelautor@gmail.com', 'Rashgaal', '1234qwer');

-- --------------------------------------------------------

--
-- Table structure for table `comentarios`
--

DROP TABLE IF EXISTS `comentarios`;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `id_comentario` int NOT NULL AUTO_INCREMENT,
  `id_entrada` int NOT NULL,
  `id_visitante` int NOT NULL,
  `contenido_comentario` text NOT NULL,
  `fecha_comentario` date NOT NULL,
  PRIMARY KEY (`id_comentario`),
  KEY `fk_entrada` (`id_entrada`),
  KEY `fk_visitante` (`id_visitante`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `comentarios`
--

INSERT INTO `comentarios` (`id_comentario`, `id_entrada`, `id_visitante`, `contenido_comentario`, `fecha_comentario`) VALUES
(10, 44, 1, 'La música de antes sí que era buena, ahora todo es ruido.', '2024-12-10'),
(11, 45, 1, 'Eso que escuchas no es música, son ruidos. Con los Beatles ya se había hecho todo.', '2024-12-10'),
(12, 46, 1, 'Si no es en vinilo, no se escucha igual.', '2024-12-10'),
(13, 47, 1, 'El reguetón es solo ruido, lo único que hacen es repetir lo mismo una y otra vez.', '2024-12-10'),
(14, 50, 1, 'La música clásica es la única que tiene valor. El resto es todo moda pasajera.', '2024-12-10'),
(15, 46, 55, 'oink!', '2024-12-25');

-- --------------------------------------------------------

--
-- Table structure for table `entradas`
--

DROP TABLE IF EXISTS `entradas`;
CREATE TABLE IF NOT EXISTS `entradas` (
  `id_entrada` int NOT NULL AUTO_INCREMENT,
  `id_autor` int NOT NULL,
  `titulo_entrada` text NOT NULL,
  `contenido_entrada` text NOT NULL,
  `fecha_creacion_entrada` date NOT NULL,
  `categoria_entrada` enum('musica','video','concierto') NOT NULL,
  `video` varchar(250) DEFAULT NULL,
  `musica` varchar(250) DEFAULT NULL,
  `imagen` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id_entrada`),
  KEY `fk_autor` (`id_autor`)
) ENGINE=InnoDB AUTO_INCREMENT=109 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `entradas`
--

INSERT INTO `entradas` (`id_entrada`, `id_autor`, `titulo_entrada`, `contenido_entrada`, `fecha_creacion_entrada`, `categoria_entrada`, `video`, `musica`, `imagen`) VALUES
(44, 1, 'Los Mejores Conciertos de Música Electrónica en 2024: No Te Los Puedes Perder', 'La música electrónica sigue conquistando escenarios en todo el mundo, y en 2024 se presentan algunos de los conciertos más esperados de los últimos años. Desde los gigantescos festivales de EDM hasta los más íntimos eventos de techno y house, cada concierto es una oportunidad única para experimentar en vivo la magia de los beats electrónicos. Los eventos de este año prometen ser espectáculos de luz, sonido y emociones, donde los asistentes pueden vivir una experiencia inmersiva que solo la música electrónica sabe ofrecer. Artistas como Carl Cox, Nina Kraviz y Charlotte de Witte están listos para llevar al público a un viaje sonoro inolvidable.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/1.jpeg'),
(45, 1, 'Las Mejores Grabaciones de Conciertos de Música Electrónica que Debes Ver', 'Si no puedes asistir a los conciertos de música electrónica en persona, no te preocupes: las grabaciones de conciertos en vivo ofrecen una excelente alternativa para experimentar la magia del evento desde casa. Con la calidad de video y sonido mejorando constantemente, ahora podemos disfrutar de los sets de los DJs más populares, los escenarios más espectaculares y los visuales más innovadores sin salir de casa. Plataformas como YouTube y Vimeo albergan una gran cantidad de grabaciones de conciertos de música electrónica que capturan toda la energía de estos eventos.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=9-Bi0O-Xb5A', NULL, './guardar_imagenes/2.jpeg'),
(46, 1, 'Los Mejores Tracks de Música Electrónica para Escuchar en 2024', 'En 2024, la música electrónica continúa evolucionando, con nuevas producciones que integran sonidos futuristas y subgéneros inesperados. Desde el regreso del tech house hasta el avance del trance y el minimal, los artistas están fusionando estilos para crear atmósferas únicas. Entre los tracks más destacados, encontramos \"Future Shock\" de Charlotte de Witte, un bombazo de techno que hace temblar los clubs. También, el hit de RÜFÜS DU SOL, \"Make it High\", que combina el house con una carga emocional impresionante.\r\n', '2024-12-04', 'musica', '', './guardar_musica/Daft Punk - Get Lucky (Official Video) feat. Pharrell Williams and Nile Rodgers.mp3', './guardar_imagenes/3.jpeg'),
(47, 1, 'Cómo Los Festivales de Música Electrónica Transforman Ciudades Enteras', 'Los festivales de música electrónica tienen un poder único para transformar no solo el paisaje sonoro, sino también el urbano. Ciudades como Barcelona, Berlín o Miami se han convertido en epicentros de la música electrónica, donde cada festival se toma como una oportunidad para revitalizar espacios y atraer a miles de personas de todo el mundo. Los festivales no solo son una escapatoria musical, sino también un fenómeno cultural que impacta en la economía local, la vida nocturna y la escena artística de la ciudad.\r\n\r\nAdemás, estos festivales tienen un impacto positivo en el turismo y la creatividad. Las ciudades anfitrionas se llenan de turistas, creativos y amantes de la música electrónica, lo que genera un ambiente vibrante y de intercambio cultural. Los festivales ofrecen más que música: son plataformas para la moda, el arte digital y la gastronomía. Sin duda, los grandes festivales de música electrónica transforman el ADN de las ciudades, ofreciendo una experiencia multisensorial que permanece mucho después de que las luces se apaguen.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/4.jpeg'),
(48, 1, 'Top 10 Videos de DJ Sets de Electrónica Más Increíbles de Todos los Tiempos', 'Desde los sets de cierre en los festivales más grandes hasta las actuaciones más íntimas en clubes underground, los DJ sets en video se han convertido en una de las formas más populares de consumir música electrónica. Los videos de estos sets capturan la habilidad técnica y la energía del DJ, transformando una simple actuación en un evento monumental. Artistas como Carl Cox, Nina Kraviz y Richie Hawtin han dejado su huella en la historia de la música electrónica con actuaciones que siguen siendo recordadas por los fanáticos en todo el mundo.\r\n\r\nEn este post, exploramos los top 10 DJ sets más inolvidables que siguen definiendo el arte de pinchar música electrónica. Desde los primeros raves de los 90 hasta los espectáculos de vanguardia actuales, cada uno de estos sets ha marcado un hito en la evolución del género, convirtiéndose en momentos clave de la historia de la música electrónica. Si eres un amante de la música electrónica, estos videos son imprescindibles para entender cómo se ha transformado la escena electrónica a lo largo de los años.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=ToP5KGej4-U', NULL, './guardar_imagenes/5.jpeg'),
(49, 1, 'La Historia del Techno: Cómo Nació el Género que Dominó el Mundo', 'El techno nació en Detroit en los años 80, impulsado por artistas como Juan Atkins, Derrick May y Kevin Saunderson. A través de una fusión de funk, disco y futurismo, el techno emergió como una respuesta a la cultura urbana industrial de la época. La historia del techno está marcada por su expansión global, que lo llevó a las pistas de baile de Berlín, Barcelona, Ibiza y más allá. Hoy en día, el techno sigue siendo el pilar de la música electrónica underground.', '2024-12-04', 'musica', '', './guardar_musica/Daft Punk - Harder, Better, Faster, Stronger (Official Video).mp3', './guardar_imagenes/6.jpeg'),
(50, 1, 'Lo Más Esperado: Los Conciertos de Techno en 2024', 'El techno sigue siendo uno de los géneros más representativos de la música electrónica, y 2024 promete ser un año lleno de conciertos y festivales dedicados a este estilo. Con artistas de renombre como Adam Beyer, Richie Hawtin y Amelie Lens, los conciertos de techno en este año se perfilan como eventos imprescindibles para los amantes de los beats profundos y oscilantes. Los escenarios de techno, generalmente caracterizados por su atmósfera oscura, minimalista y futurista, ofrecerán una experiencia única para todos los asistentes.\r\n\r\nEl techno no es solo un estilo musical, sino una subcultura que ha influenciado profundamente la escena electrónica global. Los conciertos de techno en 2024 no solo estarán marcados por sets que exploran la complejidad del sonido, sino también por innovadoras instalaciones visuales que potencian la energía del ritmo. Los asistentes a estos eventos serán testigos de cómo el techno sigue evolucionando, fusionando lo clásico con lo experimental en un escenario que promete ser uno de los más emocionantes del año.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/7.jpeg'),
(51, 1, ' El Impacto de los Videos Musicales en la Música Electrónica', 'Los videos musicales en la música electrónica son una herramienta fundamental para conectar aún más con los fans. Aunque la música electrónica es un género predominantemente auditivo, los visuales juegan un papel crucial en la experiencia global del concierto y en la creación de una atmósfera única. Desde los videos futuristas de Daft Punk hasta las colaboraciones entre DJs y VJs, los videos musicales han permitido a los artistas expresar su visión de una manera completamente nueva, fusionando el sonido con el arte visual.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=YjNmO9gw9ao', NULL, './guardar_imagenes/8.jpeg'),
(52, 1, '10 Canciones de Trance que Definieron una Década', 'El trance, con sus melodías hipnóticas y eufóricas, ha marcado a varias generaciones. Algunas de las canciones más emblemáticas incluyen “Silence” de Delerium feat. Sarah McLachlan, \"As the Rush Comes\" de Motorcycle, y “Adagio for Strings” de Tiësto. Estos temas no solo definieron el género en su momento, sino que también marcaron el pulso de una cultura rave en constante expansión.', '2024-12-04', 'musica', '', './guardar_musica/Daft Punk - Lose Yourself to Dance (Official Version).mp3', './guardar_imagenes/9.jpeg'),
(53, 1, 'Los Conciertos de Trance que Definieron la Historia de la Música Electrónica', 'El trance ha sido uno de los géneros más influyentes en la música electrónica y sus conciertos han marcado momentos clave en la historia del género. Desde los icónicos sets de Tiësto y Armin van Buuren en festivales como Tomorrowland, hasta las noches mágicas en Ibiza, los conciertos de trance han creado una comunidad global de seguidores que buscan una experiencia emocional única. La capacidad del trance para combinar melodías eufóricas con beats hipnóticos lo ha convertido en un género que perdura a lo largo del tiempo.\r\n\r\nEn estos conciertos, la conexión con la audiencia es clave: los beats no solo se escuchan, se sienten profundamente. Los conciertos de trance tienen la capacidad de transportar a los asistentes a otro mundo, un estado de trance, donde la música y las luces se fusionan en una experiencia sensorial de otro nivel. En 2024, se espera que los conciertos de trance continúen esta tradición, llevando la música electrónica a nuevas alturas y consolidando al trance como un género eterno y atemporal.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/10.jpeg'),
(54, 1, 'La Evolución de los Videos de Música Electrónica: De lo Básico a lo Espectacular', 'Los videos de música electrónica han recorrido un largo camino desde sus inicios. En sus primeras etapas, los videos musicales eran simples grabaciones de DJs mezclando detrás de sus mesas de trabajo, sin demasiados efectos visuales o una narrativa clara. Sin embargo, con el tiempo, la industria de la música electrónica ha abrazado el potencial de los efectos visuales, las proyecciones en 3D y la animación digital para crear experiencias sensoriales completas que acompañan el ritmo y la energía de la música. En la actualidad, los videos electrónicos son espectáculos visuales impresionantes que a menudo superan las expectativas de los espectadores.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=XpNAX-fEpfQ', NULL, './guardar_imagenes/11.jpeg'),
(55, 1, 'Cómo Crear una Canción de Música Electrónica: Consejos para Principiantes', 'Crear música electrónica es un proceso que combina creatividad, técnica y la comprensión de la tecnología. Comienza con la elección de un DAW (Digital Audio Workstation) como Ableton Live o FL Studio. Aprende sobre la estructura básica de una canción: intro, breakdown, build-up y drop. Familiarízate con el diseño de sonidos usando sintetizadores, y no olvides el poder de las percusiones, los bajos y las capas de efectos para dar vida a tu track.', '2024-12-04', 'musica', '', './guardar_musica/Daft Punk - One More Time (Official Video).mp3', './guardar_imagenes/12.jpeg'),
(56, 1, 'El Fenómeno de los Conciertos de Música Electrónica al Aire Libre', 'Los conciertos al aire libre de música electrónica se han convertido en una de las experiencias más buscadas por los fanáticos de los géneros electrónicos. Con escenarios espectaculares rodeados de naturaleza, estos conciertos ofrecen una sensación única de libertad y conexión con el entorno. Desde festivales masivos como Ultra Music Festival en Miami hasta eventos más pequeños y locales, los conciertos al aire libre permiten a los asistentes disfrutar de la música electrónica bajo el cielo, creando un ambiente mágico y expansivo.\r\n\r\nAdemás, la tecnología de iluminación y sonido en estos conciertos al aire libre ha avanzado tanto que ahora ofrecen experiencias inmersivas, donde los visuales y las proyecciones complementan perfectamente los sets de los DJs. Estos eventos no solo son una oportunidad para disfrutar de buena música, sino también para vivir la emoción de estar rodeado de miles de personas, todos unidos por el mismo amor por los beats y las vibraciones electrónicas. Este tipo de conciertos se han convertido en una tradición en muchas culturas y continúan atrayendo a miles de personas cada año.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/13.jpeg'),
(57, 1, 'Los 5 Mejores Documentales sobre Música Electrónica que No Te Puedes Perder', 'La música electrónica ha dejado una huella indeleble en la cultura global, y los documentales sobre este género ofrecen una mirada profunda a su historia, sus creadores y su impacto. Estos documentales no solo nos muestran el proceso detrás de la creación de la música, sino también las historias personales de los artistas que han formado la escena electrónica tal como la conocemos. Entre los documentales más populares, podemos encontrar \"What We Started\" (que sigue la evolución de la música EDM), \"Under the Electric Sky\" (sobre el fenómeno del Electric Daisy Carnival) y \"I Am Hardwell\" (una crónica de la vida del DJ Hardwell).\r\n\r\nEstos documentales son esenciales para los fanáticos que buscan entender más allá de los beats y las luces. Nos sumergen en los aspectos más humanos y artísticos de la música electrónica, mostrando la pasión, el sacrificio y la innovación que se requiere para crear sonidos que dominan las pistas de baile. Al ver estos documentales, los espectadores pueden obtener una visión más clara de la cultura que ha dado forma a la música electrónica, desde sus orígenes en Chicago y Detroit hasta su explosión en todo el mundo.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=u7ze5vOQnE4', NULL, './guardar_imagenes/14.jpeg'),
(58, 1, 'Los 5 Mejores Tracks de House que Marcaron la Evolución del Género', 'El house ha evolucionado a lo largo de las décadas, desde sus raíces en Chicago hasta convertirse en un fenómeno global. Algunos de los tracks más importantes incluyen “Your Love” de Frankie Knuckles, el himno clásico de Daft Punk “Around the World”, y “I Feel for You” de Bob Sinclar. Estos temas no solo definieron el sonido de su época, sino que también ayudaron a que el house trascendiera a la cultura popular.', '2024-12-04', 'musica', '', './guardar_musica/David Guetta - Shot Me Down ft. Skylar Grey (Lyric Video).mp3', './guardar_imagenes/15.jpeg'),
(59, 1, 'La Magia del Sonido en Vivo: Cómo los DJs Crean Experiencias Únicas en el Escenario', 'El sonido en vivo es uno de los elementos más impactantes de los conciertos de música electrónica, y los DJs tienen el poder de transformar un set en una experiencia única. En el escenario, no solo se trata de mezclar canciones; los DJs interactúan con la audiencia, creando un diálogo sonoro que se adapta a la energía del momento. Ya sea con un beat pesado de techno o con melodías envolventes de trance, la habilidad de un DJ para leer la pista de baile y ajustar el set en tiempo real es lo que hace que cada concierto sea irrepetible.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/16.jpeg'),
(60, 1, 'Guía de los Mejores Conciertos de EDM Este Año', 'La música EDM sigue siendo un fenómeno global que atrae a miles de personas a conciertos y festivales en todo el mundo. En 2024, algunos de los mejores DJs del mundo estarán presentando sus shows en eventos masivos que prometen ser espectaculares. Con carteles llenos de artistas como Martin Garrix, Marshmello, David Guetta y muchos más, los conciertos de EDM son el lugar ideal para experimentar una energía inigualable, grandes producciones visuales y, por supuesto, música que te hará bailar hasta el amanecer.\r\n\r\nAdemás, los conciertos de EDM no solo destacan por la música, sino también por sus impresionantes escenarios, efectos especiales y la atmósfera que crean. En algunos de los festivales más grandes del mundo, los asistentes podrán disfrutar de experiencias inmersivas con pantallas gigantes, láseres sincronizados y shows pirotécnicos. Estos conciertos se han convertido en eventos multimediales donde la música y la tecnología se fusionan para ofrecer un espectáculo visual y sonoro sin igual.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/17.jpeg'),
(61, 1, 'Los Conciertos Underground de Música Electrónica que Todo Amante del Género Debería Ver', 'El underground es la cuna de muchos de los subgéneros más interesantes de la música electrónica, y sus conciertos se caracterizan por su intimidad, su autenticidad y su capacidad para conectar a los artistas con su audiencia de una manera más directa. Desde fiestas clandestinas hasta clubes pequeños y llenos de energía, los conciertos underground de música electrónica ofrecen una experiencia única que se aleja de la comercialización de los grandes festivales. Estos eventos están orientados a quienes buscan un sonido más crudo, experimental y fuera de lo convencional.\r\n\r\nLo más emocionante de los conciertos underground es la sensación de pertenencia y la conexión que se crea entre los asistentes y los artistas. Los sets suelen ser más largos, las transiciones son más orgánicas y la música está menos limitada por las expectativas del público. Estos conciertos se enfocan en la esencia de la música electrónica, donde los sonidos más oscuros del techno, el house y el minimalismo dominan la pista de baile. Si eres un amante de la música electrónica en su forma más pura, no puedes dejar pasar la oportunidad de vivir una de estas experiencias.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/18.jpeg'),
(62, 1, '5 Experiencias de Rave que Van Más Allá de la Música', 'Los raves no solo se tratan de música; son una forma de expresión cultural, un espacio de libertad y creatividad donde los asistentes pueden liberarse de las normas sociales y sumergirse en una experiencia sensorial total. Los mejores raves combinan la música electrónica con arte, moda, visuales y una atmósfera única. Algunos eventos incluso incluyen instalaciones interactivas, performances de arte digital y experiencias de realidad virtual, lo que convierte a cada rave en una experiencia inmersiva más allá de la música.\r\n\r\nAdemás, los raves son una celebración de la comunidad. Los asistentes se sienten parte de algo más grande que ellos mismos, conectando con personas de todo el mundo a través de la música y el ambiente que se crea. En estos eventos, la música se convierte en una herramienta para expresar emociones, explorar nuevas formas de interacción y vivir una experiencia única que va más allá de los límites de un concierto convencional. Los raves más memorables son aquellos donde la música, el arte y la libertad se unen para crear momentos irrepetibles.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/19.jpeg'),
(63, 1, 'Cómo el Techno y el House Siguen Dominando los Escenarios Globales', 'El techno y el house siguen siendo dos de los géneros más influyentes de la música electrónica, y en 2024 continúan dominando los principales escenarios del mundo. Ambos géneros se caracterizan por sus ritmos hipnóticos y su capacidad para crear una atmósfera única en la pista de baile. Aunque nacieron en la década de los 80 y 90, el techno y el house han evolucionado y se han fusionado con otros subgéneros, manteniéndose frescos y relevantes para nuevas generaciones de amantes de la música electrónica.\r\n\r\nLos conciertos de techno y house suelen ser experiencias de inmersión total, donde los asistentes se sumergen en un mar de sonidos profundos y vibrantes. Artistas como Dixon, Solomun y Carl Cox siguen siendo figuras clave en estos géneros, ofreciendo sets que exploran las texturas más oscuras y las melodías más eufóricas. En 2024, la energía de estos géneros promete seguir siendo una de las principales razones por las que la música electrónica sigue siendo un fenómeno cultural global.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/20.jpeg'),
(64, 1, 'Rave Visuals: Cómo los Videos de Electrónica Crean una Experiencia Sensorial Única', 'Los videos de música electrónica no solo complementan las canciones, sino que crean una experiencia sensorial completa. El uso de luces, proyecciones y efectos visuales ha sido clave en la evolución de los conciertos de música electrónica. Los VJs (video jockeys) juegan un papel fundamental en la creación de estos visuales que acompañan los DJ sets, proporcionando un espectáculo que va más allá de la música. Desde las imágenes psicodélicas hasta las animaciones 3D futuristas, los videos de electrónica son tan emocionantes como la música que acompañan.\r\n\r\nAdemás, estos visuales pueden influir directamente en la atmósfera del evento, creando una atmósfera inmersiva donde los asistentes no solo escuchan la música, sino que también la ven y la sienten. La sincronización perfecta entre música y visuales convierte a los conciertos de electrónica en una experiencia holística, capaz de transportar a la audiencia a un mundo paralelo lleno de colores, luces y movimientos. Cada rave o festival se convierte en una obra de arte audiovisual que no podría existir sin la unión de sonido y visuales.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=bxYhJpILIQE', NULL, './guardar_imagenes/20.jpeg'),
(65, 1, 'Video-Entrevista con un DJ: Cómo la Tecnología Está Cambiando los Shows en Vivo', 'La música electrónica y la moda siempre han ido de la mano. Los videos de música electrónica, con su estética futurista, psicodélica y a menudo experimental, han influido profundamente en las tendencias de la moda y en la cultura visual en general. Los trajes metálicos, las gafas futuristas y el estilo urbano de los festivales se reflejan en los videoclips de artistas como The Chemical Brothers o Daft Punk, cuyas producciones visuales han dejado una marca indeleble en el mundo del diseño y la moda.\r\n\r\nAdemás, los videos musicales electrónicos suelen ser plataformas para la expresión artística, donde la ropa y los accesorios se convierten en una extensión de la narrativa visual. Al ser una forma de arte tan visual, la música electrónica se ha convertido en un motor de tendencias, con diseñadores y artistas visuales tomando inspiración directamente de estos videos para crear colecciones de moda innovadoras. Este fenómeno no solo afecta a los festivales, sino que también se ha infiltrado en el mundo de la moda urbana y el estilo de vida de los jóvenes.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=axynX-GqI5M', NULL, './guardar_imagenes/22.jpg'),
(66, 1, 'Behind the Scenes: La Creación de un Video Musical Electrónico', 'Los videos de los live sets de techno ofrecen una visión única de cómo los DJs crean su música en tiempo real. Estos sets no solo son una presentación de mezclas, sino una experiencia que se desarrolla en vivo, donde los artistas manipulan los sonidos y crean algo único en cada actuación. Ver estos videos nos permite adentrarnos en la mente del DJ y experimentar cómo construye su set, explorando capas de sonidos y jugando con la percepción del ritmo y la energía.\r\n\r\nLos visuales que acompañan a estos sets son clave para amplificar la atmósfera de techno, un género que se caracteriza por sus paisajes sonoros profundos y oscuros. Las proyecciones de luces y las imágenes hipnóticas complementan perfectamente los beats repetitivos y las transiciones largas, creando una experiencia sensorial envolvente. Los videos de live sets de techno nos permiten sentir la música de una forma más intensa, conectando visualmente con los sonidos que estamos escuchando.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=wRhrTklf1II', NULL, './guardar_imagenes/23.jpg'),
(67, 1, 'Los Mejores Videos de Música Electrónica para Relajarte y Concentrarte', 'En los festivales de música electrónica, los visuales juegan un papel fundamental para crear una atmósfera envolvente que potencie la experiencia musical. Los DJs no solo ofrecen su música en vivo, sino que las proyecciones visuales, las luces sincronizadas y los efectos especiales crean una experiencia sensorial total para el público. Estos festivales se han convertido en un espacio donde la tecnología, la música y el arte se combinan para llevar al espectador a un estado de éxtasis visual y sonoro. La creatividad de los VJs y diseñadores de luces es clave para que cada festival sea único, transformando el escenario en un espectáculo de luces y proyecciones que interactúan directamente con la música.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=UOiuw6YmfOY', NULL, './guardar_imagenes/24.jpg'),
(68, 1, 'Cómo los Videos de Música Electrónica Influencian la Moda y la Cultura Visual', 'Los avances en tecnología siguen impulsando la evolución de los videos de música electrónica. Con la integración de tecnologías como la realidad aumentada (AR) y la inteligencia artificial (IA), los videos musicales están alcanzando nuevos niveles de interactividad y creatividad. Los artistas de música electrónica están adoptando estas herramientas para crear experiencias visuales cada vez más inmersivas que no solo acompañan la música, sino que interactúan con ella de formas inéditas. Con la AR, los espectadores pueden ver elementos digitales superpuestos sobre su entorno, mientras que la IA permite generar visuales en tiempo real, adaptados a la energía de la música.\r\n\r\nEl uso de la realidad virtual (VR) también está tomando fuerza, permitiendo a los fanáticos asistir a conciertos virtuales donde pueden explorar el entorno y la acción desde diferentes perspectivas. Este tipo de experiencias va más allá de los tradicionales videoclips y abre un abanico de posibilidades para futuros lanzamientos. Los artistas, como Virtual Self de Porter Robinson o los experimentos de 3D de Amon Tobin, están liderando esta revolución digital, creando mundos virtuales donde la música electrónica se funde con la tecnología para ofrecer algo completamente nuevo y futurista.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=bjHF98-4oG0', NULL, './guardar_imagenes/25.jpg'),
(69, 1, 'La Magia de los Beats: Cómo el Ritmo Domina la Música Electrónica', 'En la música electrónica, el ritmo es el corazón palpitante que mueve todo. Los beats, creados a partir de cajas de ritmos o samples, son fundamentales en géneros como el techno, el drum and bass y el hip-hop electrónico. Desde los compases inquebrantables del techno hasta las complejas estructuras del dubstep, el ritmo no solo guía el movimiento físico en las pistas de baile, sino que también establece la atmósfera emocional del track.', '2024-12-04', 'musica', '', './guardar_musica/David Guetta & Showtek - Bad ft.Vassy (Lyrics Video).mp3', './guardar_imagenes/26.jpg'),
(70, 1, 'Explorando el Minimal Techno: El Arte de la Simplicidad Musical', 'El minimal techno se caracteriza por su enfoque en la simplicidad, utilizando pocos elementos musicales para crear un impacto profundo. Artistas como Richie Hawtin y Plastikman son pioneros de este estilo, que se enfoca en la repetición, la textura y el espacio. A pesar de su aparente simpleza, el minimal techno crea una experiencia sonora profunda que invita a la inmersión y la reflexión.', '2024-12-04', 'musica', '', './guardar_musica/Disclosure - You & Me (Flume Remix) [Official Video].mp3', './guardar_imagenes/27.jpg'),
(71, 1, 'Las Canciones Más Icónicas de Daft Punk y Su Legado en la Música Electrónica', 'Daft Punk ha sido una de las bandas más influyentes en la historia de la música electrónica. Canciones como “One More Time”, “Harder, Better, Faster, Stronger” y “Get Lucky” marcaron generaciones y sentaron las bases del electro house y el French house. Su legado no solo está en sus producciones, sino también en cómo transformaron la forma en que los artistas electrónicos se conectan con su audiencia.', '2024-12-04', 'musica', '', './guardar_musica/\'I FINK U FREEKY\' by DIE ANTWOORD (Official).mp3', './guardar_imagenes/28.jpg'),
(72, 1, 'Top 10 Canciones de EDM que Dejaron Huella en los Festivales', 'La EDM (Electronic Dance Music) se ha convertido en el centro de atención en festivales globales. Canciones como “Wake Me Up” de Avicii, “Scary Monsters and Nice Sprites” de Skrillex, y “Titanium” de David Guetta feat. Sia, marcaron la historia de los festivales, logrando conectar a miles de personas con un solo beat. Estos tracks no solo definieron el sonido de la EDM, sino que también contribuyeron a hacer de los festivales una experiencia cultural colectiva.', '2024-12-04', 'musica', '', './guardar_musica/Oliver Tree & Robin Schulz - Miss You [Official Music Video].mp3', './guardar_imagenes/29.png'),
(73, 1, 'Cómo los Subgéneros de la Música Electrónica Están Evolucionando', 'La música electrónica es vasta y compleja, con una impresionante variedad de subgéneros. En los últimos años, estilos como el future bass, el dubstep y el tropical house han crecido, mientras que géneros como el trance, el techno y el house continúan evolucionando. Artistas como Porter Robinson han llevado el future bass a nuevos niveles emocionales, y el techno sigue adquiriendo nuevas formas, fusionándose con otros estilos como el industrial y el ambient.', '2024-12-04', 'musica', '', './guardar_musica/Scooter - The Logical Song (Official Video).mp3', './guardar_imagenes/30.png'),
(74, 1, 'Los 5 Mejores Conciertos de Música Electrónica de Todos los Tiempos', 'La tecnología ha transformado por completo la manera en que experimentamos los conciertos de música electrónica. Los avances en iluminación, sonido y efectos visuales permiten que los organizadores de eventos creen experiencias inmersivas que van mucho más allá de la música. El uso de pantallas LED gigantes, tecnología de mapeo 3D y sistemas de sonido envolventes han elevado la percepción del público, convirtiendo cada evento en una obra de arte. Además, la realidad virtual y aumentada se están integrando poco a poco en los conciertos de música electrónica, permitiendo que los asistentes interactúen con el entorno y la música de formas inéditas.\r\n\r\nLa tecnología también ha permitido a los artistas crear performances más personalizadas. Los sets de los DJs ahora se pueden combinar con visuales generados en tiempo real, creando una atmósfera única para cada evento. La integración de herramientas como Ableton Live y el uso de controladores avanzados permiten a los artistas improvisar y experimentar con sonidos, lo que hace que cada presentación sea completamente única. De esta manera, la tecnología no solo mejora la experiencia para el público, sino que también permite a los artistas explorar nuevas formas de expresión creativa.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/31.png'),
(75, 1, 'El Impacto de los Conciertos Virtuales en la Música Electrónica', 'Los conciertos virtuales han crecido en popularidad, especialmente después de la pandemia, cuando muchos eventos en vivo se trasladaron al espacio digital. A través de plataformas como Twitch, YouTube y plataformas especializadas como Veeps, los artistas de música electrónica pueden conectarse con sus fans a nivel global sin importar las barreras geográficas. Estos conciertos permiten que la experiencia de un evento en vivo se lleve a todos los rincones del mundo, ofreciendo a los fanáticos una experiencia completamente digital. Además, muchos de estos conciertos incluyen interacciones en tiempo real, como chats en vivo o votaciones para que los espectadores elijan la siguiente canción.\r\n\r\nA pesar de que nada sustituye la energía de un concierto en vivo, los conciertos virtuales ofrecen una oportunidad única para descubrir nuevos artistas, explorar actuaciones exclusivas y acceder a sets especiales desde la comodidad de casa. Algunos de los mejores conciertos virtuales también se están haciendo cada vez más interactivos, permitiendo a los asistentes navegar por el evento, elegir ángulos de cámara o incluso crear sus propios avatares para bailar junto al DJ. Estos conciertos están cambiando la forma en que consumimos música electrónica, abriendo nuevas posibilidades para la comunidad global de fanáticos.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/32.png'),
(76, 1, 'La Estética Visual de los Videos de Trance: Psicodelia y Éxtasis', 'El trance ha sido uno de los géneros más visuales dentro de la música electrónica, con videos que exploran la psicodelia, lo surrealista y lo onírico. Los visuales en los videos de trance a menudo siguen un patrón de colores brillantes, formas geométricas complejas y efectos que imitan un estado de éxtasis. Estas representaciones visuales se sincronizan con las melodías eufóricas y las progresiones armónicas del trance, creando una atmósfera única que transporta al espectador a un estado casi hipnótico. Estos videos son una extensión del viaje emocional que propone la música, invitando a los espectadores a dejarse llevar por las imágenes y los sonidos.\r\n\r\nA lo largo de los años, el trance ha sido sinónimo de videos visualmente innovadores. Artistas como Above & Beyond, Paul van Dyk y Ferry Corsten han lanzado videoclips que han marcado tendencia en la estética visual del género. Los efectos psicodélicos, el uso del glitch art y las animaciones abstractas en 3D crean una experiencia que va más allá de la música, llevando al espectador a una dimensión sensorial completa. Para los fans del trance, los videos son una parte integral de la experiencia, y continúan evolucionando con las nuevas tecnologías de producción audiovisual.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=J0YZQNgkf9Y', NULL, './guardar_imagenes/33.png'),
(77, 1, 'Cómo los Videos de Electrónica Están Influenciando el Arte Digital Contemporáneo', 'La música electrónica ha tenido un gran impacto en el arte digital contemporáneo, y sus videos son una muestra de ello. Los videoclips de música electrónica, que a menudo integran efectos visuales y CGI de vanguardia, están llevando el arte digital a nuevas alturas. Artistas como Autechre, Flying Lotus y Squarepusher han trabajado con artistas visuales para crear videos que no solo son una extensión de la música, sino también una forma de arte independiente. Estos videos exploran nuevas formas de expresión artística,', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=_Ya9sjfVGSc', NULL, './guardar_imagenes/34.png'),
(78, 1, 'La Ciencia de las Frecuencias: Cómo la Música Electrónica Afecta el Cerebro', 'La música electrónica no solo es una experiencia auditiva, sino también cerebral. Las frecuencias en las que se producen los sonidos pueden influir en la actividad cerebral, generando estados de ánimo o incluso alterando la percepción del tiempo. Los bajos profundos del dubstep, las melodías repetitivas del trance y las vibraciones de las frecuencias bajas en el techno pueden generar un \"subidón\" emocional, mientras que otros géneros más tranquilos, como el ambient, inducen relajación.', '2024-12-04', 'musica', '', './guardar_musica/SKRILLEX - Bangarang feat. Sirah [Official Music Video].mp3', './guardar_imagenes/35.png'),
(79, 1, 'La Influencia de la Música Electrónica en los Géneros Pop y Hip-Hop', 'La música electrónica ha tenido una gran influencia en géneros como el pop y el hip-hop. Artistas como Calvin Harris y David Guetta han colaborado con superestrellas del pop, mientras que el hip-hop ha adoptado elementos electrónicos, como lo demuestra el trabajo de productores como Metro Boomin y Flume. La fusión de estos géneros ha llevado a la creación de sonidos híbridos que marcan la pauta de las tendencias musicales contemporáneas.', '2024-12-04', 'musica', '', './guardar_musica/Skrillex & Damian Jr. Gong Marley - Make It Bun Dem [OFFICIAL VIDEO].mp3', './guardar_imagenes/36.png'),
(80, 1, 'Los Conciertos Más Intimos de Electrónica: DJs en Pequeños Clubes', 'A pesar de la enorme popularidad de los grandes festivales de música electrónica, los conciertos en pequeños clubes siguen siendo la esencia de la música electrónica. Estos shows más íntimos permiten una conexión más cercana entre el DJ y el público, creando una atmósfera más personal y auténtica. En estos eventos, los asistentes pueden disfrutar de un sonido más crudo y menos producido, con sets improvisados y una interacción más directa con el artista. Además, los pequeños clubes a menudo tienen una vibra única, donde la energía de la pista de baile es palpable y la música se siente más intensa.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/37.png'),
(81, 1, 'El Papel de los Visuales en los Conciertos de Música Electrónica: Impacto y Creatividad', 'Los visuales en los conciertos de música electrónica juegan un papel crucial en la creación de una atmósfera única, pero también son una forma de expresión creativa que complementa la música. Los videos proyectados durante los shows en vivo no solo sirven para iluminar el escenario, sino que forman parte de una narrativa visual que se fusiona con los sonidos para crear una experiencia multisensorial. Las proyecciones de luz, las animaciones en 3D, el video mapping y los efectos especiales son solo algunas de las herramientas utilizadas por los artistas y VJs (video jockeys) para intensificar la energía del evento.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=Yg_tEq-wOXM', NULL, './guardar_imagenes/38.png'),
(82, 1, '¿Qué es el Deep House y Cómo se Está Fusionando con Otros Géneros?', 'El deep house se caracteriza por sus melodías suaves, bajos profundos y un ritmo relajado, lo que lo convierte en el subgénero perfecto para ambientes tranquilos o clubes nocturnos. En los últimos años, el deep house ha comenzado a fusionarse con géneros como el tropical house, el nu-disco y hasta el techno, creando una nueva ola de sonidos frescos y emocionales. Artistas como Disclosure y Jamie xx son exponentes de esta fusión.', '2024-12-04', 'musica', '', './guardar_musica/Tecktonik - Now you\'re gone with old song.mp3', './guardar_imagenes/39.png'),
(83, 1, 'Conciertos de Electrónica en Ambientes Naturales: Fiestas en la Playa y en la Montaña', 'Algunos de los conciertos más inolvidables de música electrónica no tienen lugar en enormes estadios o salas de conciertos, sino en entornos naturales. Las fiestas en la playa, los conciertos en montañas y los festivales en bosques están en auge, ofreciendo a los asistentes una experiencia única donde la música se fusiona con la belleza del entorno. Estos conciertos permiten disfrutar de la música electrónica bajo el cielo abierto, rodeado de la naturaleza, lo que crea una atmósfera mágica que no se encuentra en los escenarios convencionales. Los sonidos del mar o el viento se mezclan con los beats electrónicos, elevando la experiencia sensorial.\r\n\r\nAdemás, los conciertos en estos entornos naturales suelen estar más enfocados en la comunidad y en la conexión entre los asistentes. Estos eventos tienden a ser más pequeños y menos comerciales, lo que les da un aire de exclusividad y autenticidad. La combinación de la música electrónica con la naturaleza crea una energía especial que se siente única en cada festival o rave. Si buscas una experiencia diferente a los grandes eventos, estos conciertos en lugares naturales son una excelente opción.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/40.png'),
(84, 1, 'Las Mejores Experiencias de Conciertos Electrónicos para los Amantes del Minimalismo', 'El minimalismo en la música electrónica ha ganado popularidad en los últimos años, y sus conciertos ofrecen una experiencia única para aquellos que buscan un sonido más refinado y menos sobrecargado. Los conciertos minimalistas son a menudo eventos más introspectivos, donde los DJs se centran en la textura, el ritmo y la simplicidad de la música. Los asistentes pueden sumergirse completamente en las ondas sonoras, dejando de lado los efectos visuales y las producciones elaboradas para enfocarse en el sonido puro. Estos eventos pueden llevarte a un estado de trance, donde cada beat tiene una intención y cada pausa tiene su significado.\r\n\r\nLos conciertos de música minimalista ofrecen una energía diferente a la de los festivales masivos. La música no es el único foco de atención; el espacio, la atmósfera y la conexión con la audiencia son esenciales para la experiencia. Artistas como Ricardo Villalobos o Richie Hawtin han sido pioneros de este tipo de conciertos, donde el sonido se convierte en un viaje emocional que invita a la meditación y la introspección. Si eres un amante de los sonidos puristas y de la música electrónica más minimalista, estos conciertos te ofrecerán una experiencia profunda y enriquecedora.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/41.png'),
(85, 1, 'Los Videoclips Más Innovadores de Música Electrónica: Pioneros de la Estética Visual', 'Algunos de los videoclips más innovadores de la música electrónica han roto las convenciones del medio, ofreciendo experiencias visuales que van mucho más allá de la simple representación de la música. Desde los primeros experimentos visuales en los 90 hasta las producciones futuristas de la actualidad, los videoclips de electrónica han sido siempre un espacio donde la creatividad visual se encuentra con la innovación sonora. Artistas como Daft Punk, The Chemical Brothers y Justice han estado a la vanguardia de esta evolución, creando videos que no solo acompañan sus canciones, sino que cuentan historias y exploran nuevos estilos visuales.\r\n\r\nEstos videoclips a menudo juegan con la estética del cine experimental, el arte digital y el surrealismo, y se caracterizan por una gran carga conceptual que invita a la reflexión. Los videos de Daft Punk, por ejemplo, a menudo fusionan la ciencia ficción con la música electrónica, mientras que los de The Chemical Brothers y Justice exploran el absurdo, la distorsión de la realidad y lo inesperado. Este tipo de videos han influenciado no solo a otros artistas de música electrónica, sino a la industria del videoclip en general, mostrando cómo la música y el arte visual pueden convertirse en un lenguaje compartido que va más allá de lo convencional.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=IzOYNL0VHbE', NULL, './guardar_imagenes/42.png'),
(86, 1, 'La Influencia del Arte Visual Psicodélico en los Videos de Música Electrónica', 'El arte visual psicodélico ha sido una gran influencia en los videos de música electrónica, especialmente dentro de géneros como el trance, el progressive y el psytrance. Estos videos suelen estar llenos de colores vibrantes, patrones geométricos, y movimientos fluidos que acompañan las progresiones y cambios de ritmo de la música. Este tipo de estética visual busca replicar la sensación de estar en un estado alterado de conciencia, con imágenes surrealistas y secuencias visuales que crean una experiencia sensorial intensa y envolvente.\r\n\r\nArtistas como Infected Mushroom, Shpongle y Ott han trabajado con visuales psicodélicos que se mezclan perfectamente con sus composiciones electrónicas. Los videoclips de este estilo no solo son un complemento para la música, sino que son una extensión del viaje emocional que ofrece la música electrónica. En estos videos, los patrones psicodélicos y las secuencias abstractas buscan conectar al espectador con una experiencia que no se limita solo a lo visual o lo sonoro, sino que fusiona ambos para ofrecer una percepción única.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=w6K0iDsu0TM', NULL, './guardar_imagenes/43.png'),
(87, 1, 'Los Mejores Álbumes de Música Electrónica de la Última Década', 'La última década ha sido testigo de algunas de las producciones más innovadoras en la música electrónica. Entre los mejores álbumes se destacan “Random Access Memories” de Daft Punk, un trabajo que fusiona disco, funk y electrónica experimental, y “In Colour” de Jamie xx, un viaje sonoro a través del house, el dubstep y el ambient. Otros álbumes a mencionar incluyen “Migration” de Bonobo y “Skin” de Flume.', '2024-12-04', 'musica', '', './guardar_musica/The Chemical Brothers - Hey Boy Hey Girl (Official Music Video).mp3', './guardar_imagenes/44.png'),
(88, 1, 'Cómo la Música Electrónica Ha Impactado el Panorama Musical Global', 'La música electrónica no solo ha dominado las pistas de baile, sino que ha transformado la industria musical en su conjunto. Artistas de diferentes géneros han comenzado a incorporar elementos electrónicos en su música, mientras que los festivales y conciertos de música electrónica han creado una cultura global que une a personas de todas las edades y orígenes. Esto ha democratizado el acceso a la música, haciendo que la producción electrónica sea más accesible que nunca.', '2024-12-04', 'musica', '', './guardar_musica/The Prodigy - Omen (Official Video).mp3', './guardar_imagenes/45.png'),
(89, 1, 'Las Mejores Localizaciones para Conciertos de Música Electrónica en 2024', 'La localización de un concierto puede ser clave para crear una experiencia única en la música electrónica. Desde los raves clandestinos hasta los majestuosos festivales al aire libre, el entorno juega un papel fundamental en cómo los asistentes perciben el evento. En 2024, muchos de los mejores conciertos de electrónica se están llevando a cabo en lugares insólitos: castillos abandonados, islas tropicales, o antiguas fábricas industrializadas que ahora se utilizan como espacios para eventos. Estos lugares no solo aportan una atmósfera especial, sino que también reflejan el espíritu rebelde y vanguardista de la música electrónica.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/46.png'),
(90, 1, 'La Magia de los Conciertos de Electrónica en el Desierto: Un Viaje Único', 'Los conciertos de música electrónica en el desierto ofrecen una experiencia singular, donde la inmensidad del paisaje se mezcla con los beats pulsantes para crear una atmósfera que parece sacada de un sueño. Festivales como Burning Man han sido pioneros en este tipo de eventos, donde la música se fusiona con la naturaleza en un entorno que ofrece tanto belleza como misterio. El desierto, con su vastedad y soledad, se convierte en el escenario perfecto para este tipo de eventos que buscan una experiencia trascendental más allá de la fiesta convencional.\r\n\r\nAdemás de la música, la magia de estos conciertos radica en cómo la comunidad, el arte y la cultura se mezclan en estos entornos desérticos. Los asistentes no solo disfrutan de la música, sino que también participan en una experiencia colectiva de arte y creatividad. Las instalaciones interactivas, el arte visual, las experiencias de meditación y las dinámicas sociales crean una atmósfera única en la que la música electrónica se convierte en una herramienta para la exploración personal y comunitaria.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/47.png'),
(91, 1, 'Video Mapping: Una Revolución Visual en los Conciertos de Electrónica', 'El video mapping ha revolucionado la manera en que los visuales se integran en los conciertos de música electrónica. Esta técnica consiste en proyectar imágenes sobre superficies tridimensionales, creando efectos visuales dinámicos y envolventes que interactúan con el espacio. En los festivales de música electrónica, el video mapping permite que los escenarios se conviertan en lienzos gigantes, donde las proyecciones crean ilusiones ópticas, distorsionan la realidad y dan vida a los sonidos de manera espectacular.\r\n\r\nEl video mapping transforma el ambiente en algo totalmente inmersivo. Los asistentes no solo disfrutan de la música, sino que también experimentan un espectáculo visual interactivo. Durante los conciertos de artistas como Deadmau5 o Eric Prydz, la combinación de luces y video mapping lleva la experiencia a un nivel totalmente nuevo, donde el público se siente parte de un mundo virtual construido en tiempo real. Esta técnica ha elevado los conciertos de música electrónica a un nivel artístico impresionante, desdibujando los límites entre el arte digital, la música y el diseño de escenarios.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=WUtVUDzkH9U&list=PLUA68EcjOwb_MQwwGyxKoKS0MyE_D24EF', NULL, './guardar_imagenes/48.png'),
(92, 1, 'La Evolución de los Conciertos de Música Electrónica en la Era Post-Pandemia', 'La pandemia de COVID-19 cambió por completo la manera en que vivimos la música en vivo. Durante meses, los conciertos presenciales fueron cancelados y los festivales se detuvieron, lo que llevó al auge de los conciertos virtuales y transmisiones en vivo. Sin embargo, a medida que el mundo comienza a volver a la normalidad, los conciertos de música electrónica también están evolucionando. La mezcla de experiencias virtuales y presenciales ha dado paso a nuevos formatos híbridos que permiten a los fanáticos disfrutar de sus artistas favoritos tanto en el lugar como desde la comodidad de su hogar.\r\n\r\nLos festivales y conciertos en vivo han adoptado protocolos de seguridad y medidas sanitarias, pero al mismo tiempo, la tecnología ha permitido una experiencia más inclusiva y accesible. Gracias a las transmisiones en vivo, los sets en 360 grados y las experiencias de realidad aumentada, los fans que no pueden asistir físicamente a un evento siguen pudiendo disfrutar de la experiencia como si estuvieran allí. Esto ha cambiado la dinámica de los conciertos, ampliando su alcance y democratizando el acceso a los eventos, incluso en tiempos de incertidumbre.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=y0k8Akk1yN0', NULL, './guardar_imagenes/49.png'),
(93, 1, 'Explorando el Ambient: La Música Electrónica para Relajarse y Meditar', 'El ambient es uno de los géneros más introspectivos de la música electrónica, caracterizado por su enfoque en la atmósfera y las texturas sonoras más que en las melodías o los ritmos. Artistas como Brian Eno, Moby y The Orb han sido fundamentales en la popularización del ambient, creando paisajes sonoros que ayudan a la meditación y el relajamiento. Este estilo ha encontrado un lugar especial en la música para el bienestar y la relajación.', '2024-12-04', 'musica', '', './guardar_musica/Wilkinson - Afterglow.mp3', './guardar_imagenes/50.png');
INSERT INTO `entradas` (`id_entrada`, `id_autor`, `titulo_entrada`, `contenido_entrada`, `fecha_creacion_entrada`, `categoria_entrada`, `video`, `musica`, `imagen`) VALUES
(94, 1, 'De la Cabina al Estudio: Cómo se Componen los Mejores Tracks de Música Electrónica', 'La creación de un track de música electrónica comienza en la cabina del DJ, pero su evolución se da en el estudio. El proceso implica la selección de samples, la creación de beats y melodías, y la producción de sonidos únicos usando sintetizadores y efectos. Los productores también experimentan con la mezcla y la masterización para que el track suene perfecto tanto en los auriculares', '2024-12-04', 'musica', '', './guardar_musica/Underworld - Techno Shinkansen (Official Visualiser).mp3', './guardar_imagenes/51.png'),
(95, 1, 'El Renacer de los Conciertos de Música Electrónica en Clubs Íntimos', 'Mientras que los grandes festivales de música electrónica siguen siendo una enorme fuente de atracción, los conciertos en clubs íntimos están experimentando un renacimiento. Estos eventos ofrecen una atmósfera más personal y auténtica, donde los asistentes pueden experimentar la música de una manera más directa y envolvente. Los clubs pequeños permiten una mayor interacción entre el DJ y la audiencia, creando una sensación de comunidad que se pierde a menudo en los grandes festivales.\r\n\r\nAdemás, los conciertos en clubs suelen estar más enfocados en la música y la calidad del sonido, lo que permite a los asistentes disfrutar de una experiencia más profunda. Los sets son más experimentales y menos producidos, lo que ofrece un espacio para la improvisación y la creación en tiempo real. Estos eventos, más exclusivos y de carácter underground, permiten a los fanáticos conectarse con artistas emergentes y descubrir nuevas propuestas sonoras.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/53.png'),
(96, 1, 'Los Conciertos de Electrónica en Ambientes Urbanos: Raves en las Calles y Techno en Azoteas', 'La escena de la música electrónica ha encontrado en las ciudades un espacio perfecto para la expresión musical. Raves clandestinos, fiestas en azoteas y conciertos en fábricas abandonadas se han convertido en las nuevas \"raves urbanas\". Estos eventos se realizan en lugares insólitos de la ciudad, creando una sensación de descubrimiento y adrenalina. Las calles, los edificios industriales y las terrazas se transforman en escenarios vibrantes de música electrónica, donde el ambiente urbano se convierte en parte del espectáculo.\r\n\r\nEste tipo de conciertos resalta la energía de la vida nocturna de las ciudades y da rienda suelta a una creatividad desbordante. La música electrónica, acompañada de luces y visuales, se convierte en una herramienta para reconfigurar el espacio urbano, convirtiendo lugares aparentemente comunes en experiencias de otro mundo. Los fanáticos disfrutan de la sensación de exclusividad, ya que estos conciertos suelen ser eventos sorpresa o de acceso restringido, lo que les da un toque de misterio y emoción.', '2024-12-04', 'concierto', '', NULL, './guardar_imagenes/54.png'),
(97, 1, 'La Relación entre los Videojuegos y los Videos de Música Electrónica', 'La influencia de los videojuegos en los videos de música electrónica es cada vez más evidente. Muchos de los videoclips de electrónica incorporan elementos visuales inspirados en la estética de los videojuegos: gráficos en 8 bits, mundos virtuales, personajes pixelados y escenas llenas de acción interactiva. Esta fusión entre los videojuegos y la música electrónica no es casual, ya que ambos comparten una relación con lo digital y lo interactivo. Los visuales en los videos de música electrónica a menudo nos sumergen en mundos fantásticos que recuerdan a los universos virtuales de los videojuegos, creando una experiencia sensorial similar a la que vivimos cuando jugamos.\r\n\r\nArtistas como Porter Robinson y Daft Punk han utilizado este enfoque en sus videos, creando universos visuales inspirados en el gaming, con mundos imaginarios llenos de personajes digitales y efectos especiales. Esta intersección de música y videojuegos ha dado lugar a una nueva forma de contar historias a través de los videos musicales, haciendo que el espectador se sienta parte de una aventura interactiva. La combinación de música electrónica y videojuegos está creando una nueva generación de videoclips, que son tanto una experiencia auditiva como visual.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=987viwvV428', NULL, './guardar_imagenes/55.png'),
(98, 1, 'El Estilo Retro en los Videos de Electrónica: Nostalgia y Futurismo', 'El estilo retro ha resurgido en los videos de música electrónica, donde lo vintage se fusiona con lo moderno.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=5qLf3rtrxEg', NULL, './guardar_imagenes/56.png'),
(99, 1, 'La Influencia del Estilo Cyberpunk en los Videos de Música Electrónica', 'El estilo cyberpunk, con sus paisajes urbanos distópicos, luces de neón y una estética futurista y tecnológica, ha tenido una gran influencia en los videos de música electrónica. Este subgénero visual se ha convertido en un elemento clave en muchos videoclips de artistas de electrónica, especialmente dentro de géneros como el industrial, el techno y el drum & bass. Los videos con una estética cyberpunk suelen presentar ciudades futuristas, personajes en entornos urbanos decadentes, y tecnología avanzada que interactúa con la música, creando una atmósfera tensa y energética.\r\n\r\nArtistas como The Prodigy, Justice y Daft Punk han incorporado elementos cyberpunk en sus videos, explorando temas de control tecnológico, la alienación en la sociedad moderna y la revolución digital. Los paisajes urbanos iluminados por neones, la mezcla de lo humano con lo tecnológico y el enfoque en la tecnología avanzada han sido claves para darle a la música electrónica una identidad visual única y evocadora. Este estilo no solo complementa las composiciones de los artistas, sino que también amplifica el mensaje de sus canciones, invitando a los espectadores a sumergirse en un futuro alternativo donde la música, la tecnología y la cultura se entrelazan en una visión de la modernidad post-industrial.', '2024-12-04', 'video', 'https://www.youtube.com/watch?v=vcapcErivO0', NULL, './guardar_imagenes/57.png'),
(100, 1, 'La Evolución del Trap Electrónico: ¿Hacia Dónde Va Este Subgénero?', 'El trap electrónico ha vivido una rápida expansión desde sus inicios a principios de la década de 2010. Fusionando las bases del trap de Atlanta con la electrónica, ha dado lugar a un sonido pesado, con bajos profundos y tempos lentos, popularizado por artistas como RL Grime, Flosstradamus y Baauer. En la actualidad, el trap electrónico continúa evolucionando, fusionándose con géneros como el dubstep, el future bass y el reggaetón. Con la aparición de nuevas tecnologías y técnicas de producción, el trap está llevando el diseño sonoro aún más lejos, creando paisajes sonoros aún más complejos y experimentales. En el futuro, podríamos ver una mayor integración del trap con la música de vanguardia y una expansión hacia nuevos estilos híbridos.', '2024-12-04', 'musica', '', './guardar_musica/Underworld - Born Slippy [Trainspotting].mp3', './guardar_imagenes/58.png'),
(101, 1, 'Los Mejores Tracks de Dubstep para Sacudir el Piso', 'El dubstep se caracteriza por su baja frecuencia, golpes agresivos y una intensidad que sacude las pistas de baile. Entre los tracks más emblemáticos del género se encuentran \"Scary Monsters and Nice Sprites\" de Skrillex, \"Bass Head\" de Bassnectar y \"Centipede\" de Knife Party. Estos temas se destacan no solo por su pesadez, sino por la habilidad de crear una atmósfera que te hace sentir la música en todo el cuerpo. Artistas como Zeds Dead, Excision y Virtual Riot continúan empujando los límites del dubstep, integrando influencias del trap, el electro y el drum and bass, mientras que el género sigue siendo una de las fuerzas más dinámicas de la música electrónica.', '2024-12-04', 'musica', '', './guardar_musica/The Prodigy - Smack my bitch up.mp3', './guardar_imagenes/59.png');

-- --------------------------------------------------------

--
-- Table structure for table `visitantes`
--

DROP TABLE IF EXISTS `visitantes`;
CREATE TABLE IF NOT EXISTS `visitantes` (
  `id_visitante` int NOT NULL AUTO_INCREMENT,
  `nombre_visitante` varchar(30) NOT NULL,
  `email_visitante` varchar(50) NOT NULL,
  `contrasenha_visitante` varchar(20) NOT NULL,
  PRIMARY KEY (`id_visitante`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `visitantes`
--

INSERT INTO `visitantes` (`id_visitante`, `nombre_visitante`, `email_visitante`, `contrasenha_visitante`) VALUES
(1, 'Paco', 'paco@paco.com', 'paco123'),
(2, 'ainoa', 'ainoa@ainoa.com', '12345qwert'),
(3, 'Alphazap', 'ivoisey0@about.me', 'fI0%=w,TiKQ'),
(4, 'Bitwolf', 'cwinterburn1@com.com', 'oB8\'Nez(WE7&OE>P'),
(5, 'Alpha', 'mcharnick2@fc2.com', 'nB0.6&bqZpMw'),
(6, 'Sonsing', 'jpuffett3@mac.com', 'qW0*8Wc8g%4LM34'),
(7, 'Y-Solowarm', 'hdifrancesco4@state.gov', 'xT8{\'a@J'),
(8, 'Kanlam', 'bbownd5@com.com', 'iN1*sT1<4<}(t?'),
(9, 'It', 'cmayler6@people.com.cn', 'iL6\"x7f5tp'),
(10, 'Cardify', 'jrusse7@netvibes.com', 'jM4><n|8NmkZBkSc'),
(11, 'Stringtough', 'gziebart8@dell.com', 'nN9*KrMV<8/Gcxj'),
(12, 'Toughjoyfax', 'jmarishenko9@home.pl', 'wZ8+Zmv0'),
(13, 'Trippledex', 'dpidgeleya@yahoo.com', 'cI7_Ln_*s}Cg5'),
(14, 'Stringtough', 'deverexb@google.co.jp', 'sZ1H}H%7D9j'),
(15, 'Sonair', 'cswinfonc@imgur.com', 'rX5?sYAk'),
(16, 'Biodex', 'jblazejd@netscape.com', 'lM3,I.,zA(>62v#'),
(17, 'Hatity', 'tnicholese@xrea.com', 'hH3$buu>3n'),
(18, 'Lotstring', 'ariddeoughf@google.co.uk', 'eG2<FCZ`2//Lg'),
(19, 'Alphazap', 'ivoisey0@about.me', 'fI0%=w,TiKQ'),
(20, 'Bitwolf', 'cwinterburn1@com.com', 'oB8Nez(WE7&OE>P'),
(21, 'Alpha', 'mcharnick2@fc2.com', 'nB0.6&bqZpMw'),
(22, 'Sonsing', 'jpuffett3@mac.com', 'qW0*8Wc8g%4LM34'),
(23, 'Y-Solowarm', 'hdifrancesco4@state.gov', 'xT8{\'a@J'),
(24, 'Kanlam', 'bbownd5@com.com', 'iN1*sT1<4<}(t?'),
(25, 'It', 'cmayler6@people.com.cn', 'iL6\"x7f5tp'),
(26, 'Cardify', 'jrusse7@netvibes.com', 'jM4><n|8NmkZBkSc'),
(27, 'Stringtough', 'gziebart8@dell.com', 'nN9*KrMV<8/Gcxj'),
(28, 'Toughjoyfax', 'jmarishenko9@home.pl', 'wZ8+Zmv0'),
(29, 'Trippledex', 'dpidgeleya@yahoo.com', 'cI7_Ln_*s}Cg5'),
(30, 'Stringtough', 'deverexb@google.co.jp', 'sZ1H}H%7D9j'),
(31, 'Sonair', 'cswinfonc@imgur.com', 'rX5?sYAk'),
(32, 'Biodex', 'jblazejd@netscape.com', 'lM3,I.,zA(>62v#'),
(33, 'Hatity', 'tnicholese@xrea.com', 'hH3$buu>3n'),
(34, 'Lotstring', 'ariddeoughf@google.co.uk', 'eG2<FCZ`2//Lg'),
(35, 'Alphazap', 'ivoisey0@about.me', 'fI0%=w,TiKQ'),
(36, 'Bitwolf', 'cwinterburn1@com.com', 'oB8Nez(WE7&OE>P'),
(37, 'Alpha', 'mcharnick2@fc2.com', 'nB0.6&bqZpMw'),
(38, 'Sonsing', 'jpuffett3@mac.com', 'qW0*8Wc8g%4LM34'),
(39, 'Y-Solowarm', 'hdifrancesco4@state.gov', 'xT8{\'a@J'),
(40, 'Kanlam', 'bbownd5@com.com', 'iN1*sT1<4<}(t?'),
(41, 'It', 'cmayler6@people.com.cn', 'iL6\"x7f5tp'),
(42, 'Cardify', 'jrusse7@netvibes.com', 'jM4><n|8NmkZBkSc'),
(43, 'Stringtough', 'gziebart8@dell.com', 'nN9*KrMV<8/Gcxj'),
(44, 'Toughjoyfax', 'jmarishenko9@home.pl', 'wZ8+Zmv0'),
(45, 'Trippledex', 'dpidgeleya@yahoo.com', 'cI7_Ln_*s}Cg5'),
(46, 'Stringtough', 'deverexb@google.co.jp', 'sZ1H}H%7D9j'),
(47, 'Sonair', 'cswinfonc@imgur.com', 'rX5?sYAk'),
(48, 'Biodex', 'jblazejd@netscape.com', 'lM3,I.,zA(>62v#'),
(49, 'Hatity', 'tnicholese@xrea.com', 'hH3$buu>3n'),
(50, 'Lotstring', 'ariddeoughf@google.co.uk', 'eG2FCZ2Lg'),
(51, 'Ronstring', 'gtolleg@intel.com', 'qT7gyeo'),
(52, 'Cardguard', 'gkreuzerh@theguardian.com', 'qO4z4>8L'),
(53, 'Latlux', 'oayliffei@angelfire.com', 'tH0&zqOj4$Rpk'),
(54, 'Redhold', 'asaggsj@nytimes.com', 'rU7%>fg|T'),
(55, 'peppapig', 'fgfdhfgn@gmail.com', '0');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `comentarios`
--
ALTER TABLE `comentarios`
  ADD CONSTRAINT `fk_entrada` FOREIGN KEY (`id_entrada`) REFERENCES `entradas` (`id_entrada`),
  ADD CONSTRAINT `fk_visitante` FOREIGN KEY (`id_visitante`) REFERENCES `visitantes` (`id_visitante`);

--
-- Constraints for table `entradas`
--
ALTER TABLE `entradas`
  ADD CONSTRAINT `fk_autor` FOREIGN KEY (`id_autor`) REFERENCES `autor` (`id_autor`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
